XBotInterface:
  urdf_path: "**"
  srdf_path: "**"

ModelInterface:
  model_type: pin
  is_model_floating_base: true

xbotcore_device_configs:
    sim: $PWD/hal/talos_gz.yaml
    dummy: $PWD/hal/talos_dummy.yaml

xbotcore_threads:
    rt_main:  {sched: fifo , prio: 60, period: 0.0005}
    nrt_main: {sched: other, prio: 0 , period: 0.005}

xbotcore_plugins:

    homing:
        thread: rt_main
        type: homing

    zmq_io:
        thread: nrt_main
        type: zmq_io
        params:
          autostart: {type: bool, value: true}
          protocol: {type: string, value: tcp}
          tcp_state_port: {type: int, value: 5559}
          tcp_cmd_port: {type: int, value: 5558}
          tcp_service_port: {type: int, value: 5557}
          ipc_state_path: {type: string, value: /tmp/xbot2_zmq_pub.ipc}
          ipc_cmd_path: {type: string, value: /tmp/xbot2_zmq_cmd.ipc}
          ipc_service_path: {type: string, value: /tmp/xbot2_zmq_rep.ipc}

xbotcore_param:
  /xbot/hal/joint_safety/delta_check_dt: 0.1
  /xbot/hal/joint_safety/filter_autostart: {value: true, type: bool}
  /xbot/hal/joint_safety/filter_safe_cutoff_hz: {value: 5.0, type: double}
  /xbot/hal/joint_safety/filter_medium_cutoff_hz: {value: 15.0, type: double}
  /xbot/hal/joint_safety/filter_fast_cutoff_hz: {value: 25.0, type: double}
  /xbot/hal/enable_safety: {value: false, type: bool}
