motor_pd:
  "leg_left_*_joint": [300, 60]
  "leg_right_*_joint": [300, 60]
  "torso_*_joint": [400, 60]
  "arm_left_*_joint": [100, 25]
  "arm_right_*_joint": [100, 25]
  "head_*_joint": [20, 2]
  "gripper_*": [20, 2]

startup_motor_pd:
  "leg_left_*_joint": [300, 60]
  "leg_right_*_joint": [300, 60]
  "torso_*_joint": [400, 60]
  "arm_left_*_joint": [100, 25]
  "arm_right_*_joint": [100, 25]
  "head_*_joint": [20, 2]
  "gripper_*": [20, 2]
