motor_pd:
  "leg_left_*_joint": [900, 60]
  "leg_right_*_joint": [900, 60]
  "torso_*_joint": [600, 40]
  "arm_left_*_joint": [120, 8]
  "arm_right_*_joint": [120, 8]
  "head_*_joint": [30, 3]
  "gripper_*": [20, 2]

startup_motor_pd:
  "leg_left_*_joint": [700, 70]
  "leg_right_*_joint": [700, 70]
  "torso_*_joint": [500, 50]
  "arm_left_*_joint": [100, 10]
  "arm_right_*_joint": [100, 10]
  "head_*_joint": [30, 3]
  "gripper_*": [20, 2]
