motor_pd:
  "leg_left_*_joint": [300, 30]
  "leg_right_*_joint": [300, 30]
  "torso_*_joint": [300, 30]
  "arm_left_*_joint": [100, 10]
  "arm_right_*_joint": [100, 10]
  "head_*_joint": [10, 1]
  "gripper_*": [10, 1]

startup_motor_pd:
  "leg_left_*_joint": [300, 30]
  "leg_right_*_joint": [300, 30]
  "torso_*_joint": [300, 30]
  "arm_left_*_joint": [100, 10]
  "arm_right_*_joint": [100, 10]
  "head_*_joint": [10, 1]
  "gripper_*": [10, 1]
